language: python

sudo: true
fast_finish: true

matrix:
  include:
    - python: 2.7
    - python: 3.5
    - python: 3.6
    - python: 3.7
      dist: xenial
      sudo: true

before_install:
  - sudo apt-get install libsnappy-dev zlib1g-dev libbz2-dev cmake-data cmake -qq

install:
  - if [[ $TRAVIS_PYTHON_VERSION != "2.7" ]]; then pip install 'fsspec>=0.3.3'; fi
  - pip install python-snappy
  - pip install Cython
  - pip install -r requirements.txt
  - pip install .

script:
  - nosetests

after_success:
  - coveralls

branches:
  only:
    - master

notifications:
  slack: tradologics:HcnS6XusfcuS02waQPCG18oc
  webhooks:
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
